/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    Carrusel_Compo: typeof import('./src/components/Carrusel_Compo.vue')['default']
    Header_Pagina: typeof import('./src/components/Header_Pagina.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    History: typeof import('./src/components/History.vue')['default']
    InstitucionalApp: typeof import('./src/components/InstitucionalApp.vue')['default']
    ListadoUser: typeof import('./src/components/ListadoUser.vue')['default']
    LoginApp: typeof import('./src/components/LoginApp.vue')['default']
    LoginApp2: typeof import('./src/components/LoginApp2.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UsuarioApp: typeof import('./src/components/UsuarioApp.vue')['default']
    Usuarios: typeof import('./src/components/Usuarios.vue')['default']
  }
}
